### ISSUE TITLE
need help with install

### ISSUE THREAD

**Issue by Mile-Lile** [luochongjun/luci-app-dynv6#1]
@luochongjun 
Hi there, I get error when installing with opkg can you help me how to install it from github... how to grab it and install it (probably curl)

````
root@R8000:~# opkg install luci-app-dynv6

Unknown package 'luci-app-dynv6'.
Collected errors:
 * opkg_install_cmd: Cannot install package luci-app-dynv6.
 ````

**Comment by luochongjun** [comment]
You should download the installer [here](https://github.com/luochongjun/luci-app-dynv6/releases/download/v1.0.0/luci-app-dynv6_1.0.0_all.ipk) and let it be uploaded and installed via the luci page.

**Comment by Mile-Lile** [comment]
working out of the box, thank you very much. This app should be in the main openwrt repo...

![image](https://github.com/luochongjun/luci-app-dynv6/assets/12752816/4efd70ea-e8bb-4e11-986b-4d8eec1b55b8)

**Comment by Mile-Lile** [comment]
Hey @luochongjun can you make app to preserve config after reinstalation. If it is not to much effort?
Other unofficial owrt apps (e.g. luci-app-theme-argon) preserve configs and after falshing new snapshot all configs are there... token, and zone...

**Comment by luochongjun** [comment]
I can try to improve it, it shouldn't be too hard.

**Comment by Mile-Lile** [comment]
thank you very much, I appreciate it... your app is simple, only 2 strings needed to populate and everything works like a charm....
